<a href="https://colab.research.google.com/github/RupeshReddy672/SimplePrograms/blob/master/BasicNumpyPracAug18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from pprint import pprint

In [2]:
np.array([1,3,3],dtype=bool)

array([ True,  True,  True])

In [3]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
np.zeros((6,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
np.random.random((4,5))

array([[0.13540054, 0.19028602, 0.46577588, 0.68758351, 0.71208382],
       [0.08103937, 0.31123065, 0.47371468, 0.03571832, 0.31179086],
       [0.95007381, 0.94603408, 0.91658848, 0.39274845, 0.58951881],
       [0.86125737, 0.25033007, 0.5541198 , 0.78420064, 0.46721782]])

In [7]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [8]:
a1 = np.arange(8,dtype=np.int32)
a2 = np.arange(8, dtype=np.int64).reshape(2,4)
a3 = np.arange(8,dtype=np.int32).reshape(2,2,2)

In [9]:
# no of dimensions

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [10]:
#shape -basically it tells the shape of array depending on whether it is 1D ,2d, 3d,.
'''No of elements in every dimension like
In 1D array no of elements ,
In 2d it tells row and column count ,
In 3D it tells no of 2D arrays, and in each 2D  arraywith in 3D array,  no of rows and columns.
'''
print(a1.shape) #-> single value
print(a1, '\n')
print( '\n')
print(a2.shape)
print(a2)
print( '\n')
print( '\n')
print(a3.shape)
print(a3)

(8,)
[0 1 2 3 4 5 6 7] 



(2, 4)
[[0 1 2 3]
 [4 5 6 7]]




(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [11]:
#Size - Total no of items/elements in the array including in all of it
print(a1.size) #-> single value
print(a1, '\n')
print( '\n')
print(a2.size)
print(a2)
print( '\n')
print( '\n')
print(a3.size)
print(a3)

8
[0 1 2 3 4 5 6 7] 



8
[[0 1 2 3]
 [4 5 6 7]]




8
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [12]:
#Itemsize - it tells how much spaces the each item in array is occuping
print(a1.itemsize) #-> single value
print(a1, '\n')
print( '\n')
print(a2.itemsize)
print(a2)
print( '\n')
print( '\n')
print(a3.itemsize)
print(a3)

4
[0 1 2 3 4 5 6 7] 



8
[[0 1 2 3]
 [4 5 6 7]]




4
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [13]:
#dtype
print(a1.dtype) #-> single value
print(a1, '\n')
print( '\n')
print(a2.dtype)
print(a2)
print( '\n')
print( '\n')
print(a3.dtype)
print(a3)

int32
[0 1 2 3 4 5 6 7] 



int64
[[0 1 2 3]
 [4 5 6 7]]




int32
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [14]:
#astype
'''  change the type of data/element/variable  '''

print(a2.dtype)
a2 = a2.astype(np.int32)
a2.dtype

int64


dtype('int32')

# Array Operations

In [15]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1,'\n\n', a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [16]:
# scalar Operations

#arithemetic Operations
'''print(a1 + 2)

print(a1 - 2)
print(a1 * 2)
print(a1 / 2)
print(a1 ** 2)
print(a1 % 2)
'''

#relational

print(a2 == 15)
#print(a2 < 15)
#print(a2 >= 15)
#print(a2 <= 15)
#print(a2 == 15)
#print(a2 != 15)

[[False False False  True]
 [False False False False]
 [False False False False]]


In [17]:
#vector Operations

#arthemetic
a1*a2 #2 items should have same shape.


array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [18]:
w3 = np.arange(12).reshape(4,3)

In [19]:
a2*w3

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [20]:
a = np.random.random((3,4))
a = np.round(a*100)
a


array([[78., 91., 37., 58.],
       [ 2., 82., 93.,  3.],
       [27., 62., 75.,  4.]])

In [21]:
#max/min/sum/prod functions in numpy to perform on arrays

#on total array

np.max(a)

#on axis like x axis axis=1, y axis=0

np.max(a,axis=1)

array([91., 93., 75.])

In [22]:
#statisticsfunctions in numpy to perform on arrays
# mean/median/std/var


#mean
#on total array
print('mean')
r = np.round(np.mean(a),2)
print(a,'\n\n')
print(r)


#on axis like x axis axis=1, y axis=0

print(np.mean(a,axis=1)) #x axis
print(np.mean(a,axis=1)) # y axis
print('\n\n')


#median
#on total array
print('median')
print(a,'\n\n')
r = np.round(np.median(a),2)
print(r)


#on axis like x axis axis=1, y axis=0

print(np.median(a,axis=1)) #x axis
print(np.median(a,axis=1)) # y axis




mean
[[78. 91. 37. 58.]
 [ 2. 82. 93.  3.]
 [27. 62. 75.  4.]] 


51.0
[66. 45. 42.]
[66. 45. 42.]



median
[[78. 91. 37. 58.]
 [ 2. 82. 93.  3.]
 [27. 62. 75.  4.]] 


60.0
[68.  42.5 44.5]
[68.  42.5 44.5]


In [23]:
#trignometric functions
#sin/cos/
np.sin(a)

array([[ 0.51397846,  0.10598751, -0.64353813,  0.99287265],
       [ 0.90929743,  0.31322878, -0.94828214,  0.14112001],
       [ 0.95637593, -0.7391807 , -0.38778164, -0.7568025 ]])

In [24]:
#dot product
'''for dot product the no of rows of first array should be equal to no of columns of second array.
starting with,
1st element = (1 row of 1st arr) x (1 col of 2nd array for 1st element),
2nd element = 1arr 1 row X 2 arr 2 col, ......
12 element = 1arr 3 row X 2 aarr 3 col '''


a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(4,3)
print(a4,'\n\n',a5,'\n\n')




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 




In [25]:
np.dot(a4,a5)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [26]:
np.dot(a5,a4)

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

In [27]:
#log and exponents

np.log( a2)

array([[2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422]])

In [28]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [31]:
res = np.random.random((4,3))*100
print(res, end='\n\n')

[[14.95789814 25.18336754 97.23696494]
 [87.4362946  28.52119938  9.71040392]
 [ 2.97067313 59.71482334 32.57308471]
 [20.52227595 54.29467625 38.16045737]]



In [34]:
#round/floor/ceil


print(np.round(res), end='\n\n')
print(np.floor(res), end='\n\n')
print(np.ceil(res), end='\n\n')

[[15. 25. 97.]
 [87. 29. 10.]
 [ 3. 60. 33.]
 [21. 54. 38.]]

[[14. 25. 97.]
 [87. 28.  9.]
 [ 2. 59. 32.]
 [20. 54. 38.]]

[[15. 26. 98.]
 [88. 29. 10.]
 [ 3. 60. 33.]
 [21. 55. 39.]]



In [35]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [37]:
a6 = np.arange(27).reshape((3,3,3))
a6

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [38]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
#manipulating 2D or multidimensional arrays
#arr[row_numver, col_num]

a2[::2, ::3 ] # 1st, 3rd rows,and only columns 1,4.


array([[ 0,  3],
       [ 8, 11]])

In [41]:
print(a2[::2,1::2])

[[ 1  3]
 [ 9 11]]


In [42]:
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [43]:
a6

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [44]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [45]:
a6

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [46]:
a6[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [48]:
print(a)
print('\n')
print(a1)
print( '\n')
print(a2)
print('\n')
print(a6)

[[78. 91. 37. 58.]
 [ 2. 82. 93.  3.]
 [27. 62. 75.  4.]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [49]:
for i in a1:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [50]:
for i in a2:
  print(i,'\n')

[0 1 2 3] 

[4 5 6 7] 

[ 8  9 10 11] 



In [51]:
for i in a6:
  print(i,'\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 9 10 11]
 [12 13 14]
 [15 16 17]] 

[[18 19 20]
 [21 22 23]
 [24 25 26]] 



In [111]:
for i in np.nditer(a6): # pronounced as nd  iter "np.nditer", it will converts the n dimensional  earray to lements into  1D array.
  print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [53]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
#reshape -> already learned like np.arange(12).reshape(3,4)

In [112]:
#transpose ==>> transfers the rows to columns and columns to rows.

np.transpose(a2)
# or we can do it in a shortcut too

a2.T
# any one of these syntaxes  works.

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [57]:
#ravel ==> convert any n dimesional array to 1D array unlike nditer.
print(a6.ravel())

# flattern
a6.flatten()


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
help(np.ravel)

In [ ]:
import numpy as np

# Create a 2x3 starting array
# [[1, 2, 3],
#]
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array:")
print(arr)

# 1. 'C' Order (Row-Major)
print("\n'C' Order (Row by Row):")
print(arr.ravel(order='C'))

# 2. 'F' Order (Column-Major)
print("\n'F' Order (Column by Column):")
print(arr.ravel(order='F'))

# 3. 'K' Order (Memory Layout Order)
print("\n'K' Order (True Memory Layout):")
print(arr.ravel(order='K'))

In [ ]:
import numpy as np

original = np.array([[1, 2], [3, 4]])

# --- Case 1: Using flatten() ---
flat_arr = original.flatten()
print('flatten Array\n')
flat_arr[0] = 99
print(flat_arr,'\n\n')
print('original\n\n',original,'\n\n')
# Output: 1 (The original is safe and unchanged!)

print('ravel Array\n')
# --- Case 2: Using ravel() ---
ravel_arr = original.ravel()
print(ravel_arr,'\n\n')
ravel_arr[0] = 99
print('original\n\n',original)
# Output: 99 (The original array was changed!)

In [87]:
a7 = np.arange(12).reshape(3,4)
a8 = np.arange(12,24).reshape(3,4)
print(a7,'\n\n',a8)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [97]:
#stacking ->
'''adding or joining 2 or more arrays. it can be donehorizontal or vertical..
example joining/stacking 2x2 array with 2x2 it will make a 2x4 or a 4x2 array
( joining rows of 1st arr to left 2nd to the right).
'''
#horizontal stacking -   stacking 2x2 array with 2x2 it will make a 2x4 array. (side by side)

a9 = np.hstack((a7,a8))
a9

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [95]:
np.hstack((a7,a8,a7,a8))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [98]:
#vertical stacking -  like stacking 2x2 array with 2x2 it will make a 4x2 array.(top-bottom, row of  1st arr on top 2nd on bottom)

a10 = np.vstack((a7,a8))
a10





array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [101]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
#spliting arrays - reverse of stacking.
'''but here spliting requires equal no of division.
like 4/2, 9/3, or spliting 3 rows into 1 each row etc. but not unequal parts like 2/3, 4/5 etc.
'''
#horizontal split or hsplit
print(np.hsplit(a9,2))


[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]


In [107]:
np.hsplit(a4,5) # this gives error

ValueError: array split does not result in an equal division

In [108]:
#vertical splitting or vsplit
np.vsplit(a10,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [109]:
np.vsplit(a7,2)

ValueError: array split does not result in an equal division